package com.nam.srv42.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Record service. Represents a row in the &quot;srvv_Record&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nam.srv42.model.impl.RecordModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nam.srv42.model.impl.RecordImpl}.
 * </p>
 *
 * @author hp
 * @see Record
 * @see com.nam.srv42.model.impl.RecordImpl
 * @see com.nam.srv42.model.impl.RecordModelImpl
 * @generated
 */
public interface RecordModel extends BaseModel<Record>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a record model instance should use the {@link Record} interface instead.
     */

    /**
     * Returns the primary key of this record.
     *
     * @return the primary key of this record
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this record.
     *
     * @param primaryKey the primary key of this record
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this record.
     *
     * @return the uuid of this record
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this record.
     *
     * @param uuid the uuid of this record
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the record ID of this record.
     *
     * @return the record ID of this record
     */
    public long getRecordId();

    /**
     * Sets the record ID of this record.
     *
     * @param recordId the record ID of this record
     */
    public void setRecordId(long recordId);

    /**
     * Returns the group ID of this record.
     *
     * @return the group ID of this record
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this record.
     *
     * @param groupId the group ID of this record
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this record.
     *
     * @return the company ID of this record
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this record.
     *
     * @param companyId the company ID of this record
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this record.
     *
     * @return the user ID of this record
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this record.
     *
     * @param userId the user ID of this record
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this record.
     *
     * @return the user uuid of this record
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this record.
     *
     * @param userUuid the user uuid of this record
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this record.
     *
     * @return the user name of this record
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this record.
     *
     * @param userName the user name of this record
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this record.
     *
     * @return the create date of this record
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this record.
     *
     * @param createDate the create date of this record
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this record.
     *
     * @return the modified date of this record
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this record.
     *
     * @param modifiedDate the modified date of this record
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this record.
     *
     * @return the name of this record
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this record.
     *
     * @param name the name of this record
     */
    public void setName(String name);

    /**
     * Returns the date of this record.
     *
     * @return the date of this record
     */
    public Date getDate();

    /**
     * Sets the date of this record.
     *
     * @param date the date of this record
     */
    public void setDate(Date date);

    /**
     * Returns the employer of this record.
     *
     * @return the employer of this record
     */
    @AutoEscape
    public String getEmployer();

    /**
     * Sets the employer of this record.
     *
     * @param employer the employer of this record
     */
    public void setEmployer(String employer);

    /**
     * Returns the salary of this record.
     *
     * @return the salary of this record
     */
    public int getSalary();

    /**
     * Sets the salary of this record.
     *
     * @param salary the salary of this record
     */
    public void setSalary(int salary);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.nam.srv42.model.Record record);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.nam.srv42.model.Record> toCacheModel();

    @Override
    public com.nam.srv42.model.Record toEscapedModel();

    @Override
    public com.nam.srv42.model.Record toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
